presets:
  global:
    cookies: ~/.flexget/private/cookies.sqlite
    download: ~/Downloads/.
    # include: [ private/email.yml ]

  torrents:
    regexp:
      reject:
        - '(?x) [\W_] nuked (?:_|\b)'
      from: title
    content_filter:
      require: [ '*.avi', '*.mkv', '*.mp4', '*.rar' ]
    torrent_scrub: on
    torrent_alive: { min_seeds: 5, reject_for: 10 minutes }
    exec:
      on_output:
        for_accepted: |
          growlnotify -t 'FlexGet: torrent from {{feed}}' -m \
            '{{ title | re_replace("['']", "") }}' >/dev/null 2>&1
          tmux display-message 'FlexGet: {{feed}}: {{
            title | re_replace("['']", "") }}' >/dev/null 2>&1
        phase: |
          # This is also run from cron every few minutes.
          nice -n 20 transmission-watchdog

  tv:
    content_size: { min: 25, max: 1750 }
    manipulate:
      # Remove description field to avoid false matches from series plugin.
      - description: { remove: yes }

  tv-series:
    series:
      settings:
        tv: &TV_SETTING
          quality: dsr+ <=720p
          timeframe: 6 hours
          target: <720p
          propers: 6 hours
          specials: no
          path: ~/Media/TV/{{series_name}}/.
        animation:
          << : *TV_SETTING
          quality: hdtv+ <=720p
          path: ~/Media/TV/Animation/{{series_name}}/.
        documentaries:
          << : *TV_SETTING
          path: ~/Media/TV/Documentaries/{{series_name}}/.
        foreign:
          << : *TV_SETTING
          path: ~/Media/TV/Foreign/{{series_name}}/.
        talk_shows:
          << : *TV_SETTING
          path: ~/Media/TV/Talk Shows/{{series_name}}/.
    include: [ private/series.yml ]
    if:
      # Reject season previews or recaps.
      - ? 'has_field("series_season")
             and 1 < series_season and 0 == series_episode'
        : reject

  # Grab the first episode of any new series.
  tv-premieres:
    series_premiere:
      << : *TV_SETTING
      allow_seasonless: yes
      path: ~/Media/TV/_NEW_/.
    regexp:
      reject:
        - '(?x) (?:_|\b) (?: pdtv | au | nz | ufc | sports | championships?
                             | 24(?:h|-7) | bake | baking ) (?:_|\b)'
        - '(?x) (?:_|\b) (?: brit(?: ish | ain | annia) | england | australia
                             | norwegian | kitchen | food | cook )'
      from: title

  movies:
    interval: 30 minutes
    quality: hdtv+ <720p
    regexp:
      reject:
        - '(?x) [\W_] (?: read[\W_]*nfo | 3-?D(?:BD)? ) (?:_|\b)'
        - ? '(?x) [\W_] (?: dubbed | pldub | cropped | (?:heb|kor|swe)sub )
                (?:_|\b)'
          : { from: [ title, description ] }
        # Avoid certain groups.
        - '(?x) [\W_] (?: maxspeed | tnt[\W_]*village | cocain | wdr )
                (?:_|\b)'
      from: title
    content_size: { min: 300, max: 2500 }
    imdb_lookup: yes
    seen_movies: strict
    if:
      - not has_field('imdb_id'): reject
      - 'imdb_year < now.year - 6': reject
      - ? "sorted(imdb_genres) in [['music'], ['biography', 'music'],
            ['documentary', 'music'], ['biography', 'documentary', 'music']]"
        : reject
      - "'musical' in imdb_genres": reject
      # Probably a standup comedy.
      - "'comedy' in imdb_genres and 1 == len(imdb_actors)": reject
      - "'english' == (imdb_languages or ['english'])[0]":
          set: { path: ~/Media/Movies/. }
          imdb:
            min_score: 6.2
            min_votes: 500
      - "'documentary' in imdb_genres":
          set: { path: ~/Media/Movies/Documentaries/. }
      - "'english' != (imdb_languages or ['english'])[0]":
          set:
            path: ~/Media/Movies/Foreign/{{imdb_languages[0] | capitalize}}/.
          imdb:
            min_score: 6.8
            min_votes: 100
            accept_languages: [
              cantonese, chinese, danish, dutch, french, german, icelandic,
              italian, norwegian, japanese, korean, mandarin, portuguese,
              spanish, swedish ]
          regexp:
            reject_excluding:
              - '(?x) ^ (?: action | adventure | comedy | crime | mystery
                            | sci-fi | thriller | war ) $'
            from: imdb_genres

feeds:
  ###########
  # TV series
  ###########
  eztv:
    priority: 1
    interval: 5 minutes
    rss:
      url: http://ezrss.it/feed/
      title: filename
      silent: yes
    preset: [ torrents, tv, tv-series ]
  btn:
    priority: 2
    interval: 5 minutes
    include: [ private/btn-rss.yml ]
    preset: [ torrents, tv, tv-series ]
    manipulate:
      # Use the scene release name.
      - title: { extract: '.*\[ (.+?) \] *$' }
  xspeeds_tv:
    priority: 3
    interval: 5 minutes
    include: [ private/xspeeds_tv-rss.yml ]
    preset: [ torrents, tv, tv-series ]
  torrentday_tv:
    priority: 4
    interval: 5 minutes
    include: [ private/torrentday_tv-rss.yml ]
    preset: [ torrents, tv, tv-series ]
  thebox:
    # Ratio-based tracker; easy to maintain. UK content.
    priority: 5
    interval: 15 minutes
    rss:
      url: http://thebox.bz/rss.php?feed=dl&cat[]=14&cat[]=18&cat[]=31&cat[]=8
      silent: yes
    preset: [ torrents, tv, tv-series ]
    disable_plugin: [ torrent_alive ]
    if: [ "str(now.year) + ')' not in title": reject ]
  bitmetv:
    # Ratio-based tracker; hard to maintain.
    priority: 7
    interval: 5 minutes
    delay: 10 minutes
    include: [ private/bitmetv-rss.yml ]
    preset: [ torrents, tv, tv-series ]

  #####################
  # TV series premieres
  #####################
  btn_premieres:
    priority: 22
    interval: 5 minutes
    include: [ private/btn-rss.yml ]
    preset: [ torrents, tv, tv-premieres ]
    manipulate:
      - year: { from: title, extract: '^[^[]+\[ (\d{4}) \]' }
      # Use the scene release name.
      - title: { extract: '.*\[ (.+?) \] *$' }
      # Remove backslashes and apostrophes.
      - title: { replace: { regexp: '[\\'']+', format: '' } }
      # Normalize '&' and '&amp;' to 'and'.
      - title: { replace: { regexp: '\s*&(?:amp;)?\s*', format: ' and ' } }
    # Run if filter before series filter.
    plugin_priority: { if: 130 }
    if:
      # Accept only the current year, respecting dates near the boundary.
      - ? 'int(year) not in [(now + timedelta(n)).year for n in (0, -30, 30)]'
        :  reject
  torrentday_tv_premieres:
    priority: 23
    interval: 5 minutes
    include: [ private/torrentday_tv-rss.yml ]
    preset: [ torrents, tv, tv-premieres ]

  ########
  # Movies
  ########
  xspeeds_movies:
    priority: 31
    include: [ private/xspeeds_movies-rss.yml ]
    preset: [ torrents, movies ]
  ilt_movies:
    priority: 32
    include: [ private/ilt_movies-rss.yml ]
    preset: [ torrents, movies ]
  torrentday_movies:
    priority: 33
    include: [ private/torrentday_movies-rss.yml ]
    preset: [ torrents, movies ]
  # Foreign: AsiaTorrents.com and EUTorrents.com
  avistaz:
    priority: 35
    sequence:
      - rss: { url: 'http://feeds.feedburner.com/eutorrentsbt', silent: yes }
      - rss: { url: 'http://feeds.feedburner.com/btavistaz',    silent: yes }
    preset: [ torrents, movies ]
    urlrewrite:
      site:
        regexp: '(?x) ^ http:// (?P<host>[^/]+) .*? &id= (?P<id>[^&]+)'
        format: 'http://\g<host>/download.php?id=\g<id>&f=\g<id>.torrent'
    regexp:
      reject_excluding:
        - '(?x) \b english \b': { from: [ title, description ] }
      reject:
        - ? '(?x) \b (?: dubbed  | episodes | broadcast \W+ network
                         | tv \W+ program | air \W+ (?:date | time) ) \b'
          : { from: [ title, description ] }
