presets:
  global:
    cookies: ~/.flexget/private/cookies.sqlite
    download: ~/Downloads/.

  movies:
    interval: 30 minutes
    quality:
      max: bdrip
      min: dvdscr
    regexp:
      reject:
        - '[\W_]read[\W_]*nfo(?:_|\b)':      { from: title }
        - '[\W_]3-?D(?:BD)?(?:_|\b)':        { from: title }
        - '[\W_](?:heb|kor|swe)sub(?:_|\b)': { from: title }
        - '[\W_](?:dubbed|pldub|hardcoded|hardsubs?)(?:_|\b)':
            from: [ title, description ]
      from: title
    content_size:
      min: 650
      max: 1750
    seen_movies: strict
    imdb_required: yes
    if:
      - 'imdb_year < now.year - 6': reject
      - "['music'] == imdb_genres": reject
      - musical in imdb_genres: reject
      # Probably a standup comedy.
      - "'comedy' in imdb_genres and 1 == len(imdb_actors)": reject
      - 'True':
          set: { path: ~/Media/Movies/. }
      - "'documentary' in imdb_genres":
          set: { path: ~/Media/Movies/Documentaries/. }
      - "'english' == (imdb_languages or ['english'])[0]":
          imdb: { min_score: 6.2, min_votes: 250 }
      - "'english' != (imdb_languages or ['english'])[0]":
          set: { path: ~/Media/Movies/Foreign/. }
          imdb:
            min_score: 6.8
            min_votes: 100
            accept_languages: [
              cantonese, danish, dutch, french, german, italian, japanese,
              korean, mandarin, portuguese, spanish
            ]
          regexp:
            reject_excluding:
              - 'action|adventure|comedy|crime|mystery|sci-fi|thriller|war':
                  from: imdb_genres

  tv:
    content_size:
      min: 50
      max: 1500
    manipulate:
      # Recognize the quality of a particular ripper.
      - title:
          replace:
            regexp: (?i)ws\.xvid-err0001
            format: hdtv
      # Clean description field to avoid false matches from series plugin.
      - description: { from: title }
      - description: { extract: '' }

  tv-series:
    series:
      settings:
        tv:
          min_quality: dsr
          max_quality: bdrip
          path: ~/Media/TV/{{series_name}}/.
          propers: 3 hours
        documentaries:
          min_quality: dsr
          max_quality: bdrip
          path: ~/Media/TV/Documentaries/{{series_name}}/.
          propers: 3 hours
        talk_shows:
          min_quality: dsr
          max_quality: bdrip
          path: ~/Media/TV/Talk Shows/{{series_name}}/.
          propers: 3 hours
    include: [ private/series.yml ]
    # Reject season previews or recaps.
    if: [ '1 < series_season and 0 == series_episode': reject ]

  # Grab the first episode of any new series.
  tv-premieres:
    series_premiere:
      min_quality: dsr
      max_quality: dvdrip
      path: ~/Media/TV/_NEW_/.
      propers: no
      allow_seasonless: yes
    regexp:
      reject: [ '\d{4}(\W*)\d{2}\1\d{2}.*\bpart' ]
      from: title
    include: [ private/series_premiere.yml ]

  torrents:
    regexp:
      reject:
        - '[\W_]+(?:[hx][.-]?264|nuked)(?:_|\b)'
      from: title
    content_filter:
      reject: [ '*.m[4k]v', '*.mp4', '*.wmv' ]
    torrent_scrub: on
    torrent_alive: 5
    exec:
      auto_escape: yes
      on_output:
        for_accepted: |
          growlnotify -t FlexGet:\ torrent\ from\ {{feed}} -m {{title}} \
            >/dev/null 2>&1
          tmux display -t FlexGet:\ torrent\ from\ {{feed}} -m {{title}} \
            >/dev/null 2>&1
        phase: |
          # This is also run from cron every few minutes.
          nice -n 20 transmission-watchdog

feeds:
  ###########
  # TV series
  ###########
  eztv:
    priority: 1
    interval: 5 minutes
    rss:
      url: http://ezrss.it/feed/
      silent: yes
    preset: [ torrents, tv, tv-series ]
  btn:
    priority: 2
    interval: 5 minutes
    include: [ private/btn-rss.yml ]
    preset: [ torrents, tv, tv-series ]
    # Use the scene release name.
    manipulate:
      - title: { extract: '\[ ([^]]+) \] *$' }
  torrentday_tv:
    priority: 3
    interval: 5 minutes
    include: [ private/torrentday_tv-rss.yml ]
    preset: [ torrents, tv, tv-series ]
  thebox:
    # Ratio-based tracker; easy to maintain. UK content.
    priority: 4
    interval: 15 minutes
    rss:
      url: http://thebox.bz/rss.php?feed=dl&cat[]=14&cat[]=18&cat[]=31&cat[]=8
      silent: yes
    preset: [ torrents, tv, tv-series ]
    disable_plugin: [ torrent_alive ]
    if: [ "str(now.year) + ')' not in title": reject ]
    regexp:
      reject_excluding: [ '\((?:XviD|DivX)\)' ]
      from: title
  bitmetv:
    # Ratio-based tracker; hard to maintain.
    priority: 6
    interval: 5 minutes
    delay: 10 minutes
    include: [ private/bitmetv-rss.yml ]
    preset: [ torrents, tv, tv-series ]

  #####################
  # TV series premieres
  #####################
  btn_premieres:
    priority: 22
    interval: 5 minutes
    include: [ private/btn-rss.yml ]
    preset: [ torrents, tv, tv-premieres ]
    # Use the scene release name.
    manipulate:
      - title:
          replace:
            regexp: '^[^[]+\[ (\d+) \].*?\[ ([^]]+) \] *$'
            format: '\2 \1'
    if: [ "not title.endswith(str(now.year))": reject ]
  torrentday_tv_premieres:
    priority: 23
    interval: 5 minutes
    include: [ private/torrentday_tv-rss.yml ]
    preset: [ torrents, tv, tv-premieres ]

  ########
  # Movies
  ########
  xspeeds_movies:
    priority: 31
    include: [ private/xspeeds_movies-rss.yml ]
    preset: [ torrents, movies ]
  ilt_movies:
    priority: 32
    include: [ private/ilt_movies-rss.yml ]
    preset: [ torrents, movies ]
  torrentday_movies:
    priority: 33
    include: [ private/torrentday_movies-rss.yml ]
    preset: [ torrents, movies ]
  rlslog_movies:
    priority: 34
    rlslog: http://www.rlslog.net/category/movies/
    preset: [ torrents, movies ]
  # Foreign: AsiaTorrents.com and EUTorrents.com
  avistaz:
    priority: 35
    sequence:
      - rss: { url: 'http://feeds.feedburner.com/eutorrentsbt', silent: yes }
      - rss: { url: 'http://feeds.feedburner.com/btavistaz',    silent: yes }
    preset: [ torrents, movies ]
    urlrewrite:
      site:
        regexp: '^http://(?P<host>[^/]+).*?&id=(?P<id>[^&]+)'
        format: 'http://\g<host>/download.php?id=\g<id>&f=\g<id>.torrent'
    if: [ "'English' not in description": reject ]
