---
presets:
  global:
    download: ~/Downloads/.

  movies:
    interval: 30 minutes
    content_size:
      min: 650
      max: 1750
    regexp:
      reject_excluding:
        - '[\W_]+(?:r5|b[dr]rip|dvd(?:rip|scr))':
            from: title
    seen_movies: strict
    imdb:
      min_score: 6.2
      min_votes: 100
      min_year: 2006
      reject_genres:
        - music
        - musical
    custom_movie_path:
      default: ~/Media/Movies/.
      documentary: ~/Media/Movies/Documentaries/.
      foreign: ~/Media/Movies/Foreign/.

  tv:
    content_size:
      max: 1500
    series:
      settings:
        tv:
          path: ~/Media/TV/%(series_name)s/.
          propers: 3 hours
        documentaries:
          path: ~/Media/TV/Documentaries/%(series_name)s/.
          propers: 3 hours
        talk_shows:
          path: ~/Media/TV/Talk Shows/%(series_name)s/.
          propers: 3 hours
    include:
      - private/series.yml

  tv-new:
    # Grab the first episode of any new series.
    series_premiere: yes
    regexp:
      reject:
        - '[\W_]+(?:AU(?:TV)?|Australia(?:n|''?s)?)[\W_]+'
    set:
      path: ~/Media/TV/_NEW_/.

  torrents:
    regexp:
      reject:
        - '[\W_]+x264'
        - '[\W_]+(?:72|108)0p'
        - '[\W_]+nuked'
    # TODO: expand the folder in the finder
    adv_exec:
      on_output:
        for_accepted: |
          growlnotify -t \'FlexGet: torrent downloaded\' -m "%(title)s"
            >/dev/null 2>&1
        event: |
          # This is also run from cron every few minutes.
          nice -n 19 transmission-watchdog 2>&1 |
            tee -a /tmp/transmission-watchdog.log |
            # Need to verify some input is present because growlnotify is happy
            # displaying empty messages.
            while read -r l; do
              growlnotify -t 'transmission-watchdog via flexget' -m "$l" \
                >/dev/null 2>&1
            done

feeds:
  # TV series.
  torrentvault_tv:
    priority: 1
    interval: 5 minutes
    include:
      - private/torrentvault_tv-rss.yml
    preset:
      - torrents
      - tv
  supertorrents_tv:
    priority: 2
    interval: 5 minutes
    include:
      - private/supertorrents_tv-rss.yml
    preset:
      - torrents
      - tv
  scenetime_tv:
    priority: 3
    interval: 5 minutes
    include:
      - private/scenetime_tv-rss.yml
    preset:
      - torrents
      - tv
  eztv:
    priority: 4
    interval: 10 minutes
    rss:
      url: http://ezrss.it/feed/
      silent: yes
    preset:
      - torrents
      - tv
    remove_trackers:
      - hexagon\.cc
      - '\.onion:'
      - tor2web\.com
  thebox:
    priority: 5
    interval: 15 minutes
    rss:
      url: http://thebox.bz/rssdd.xml
      silent: yes
    include:
      - private/thebox-headers.yml
    preset:
      - torrents
      - tv
    regexp:
      reject_excluding:
        - 201\d\).*?\((?:XviD|DivX)\).*?\((?:Drama|Horizon|Mystery)
  theempire:
    priority: 6
    interval: 15 minutes
    rss:
      url: http://theempire.bz/rssdd.xml
      silent: yes
    include:
      - private/theempire-headers.yml
    preset:
      - torrents
      - tv
    regexp:
      reject_excluding:
        - 201\d\).*?\((?:XviD|DivX)\).*?\((?:Documentary|Drama|Mystery)

  # TV series premieres.
  torrentvault_tv_new:
    interval: 5 minutes
    include:
      - private/torrentvault_tv-rss.yml
    preset:
      - torrents
      - tv-new
  supertorrents_tv_new:
    interval: 5 minutes
    include:
      - private/supertorrents_tv-rss.yml
    preset:
      - torrents
      - tv-new
  torrentday_tv_new:
    interval: 5 minutes
    include:
      - private/torrentday_tv-rss.yml
    preset:
      - torrents
      - tv-new
  eztv_new:
    interval: 10 minutes
    rss:
      url: http://ezrss.it/feed/
      silent: yes
    # The series_premiere plugin will only look at the entry title, but this
    # feed uses a non-standard title format. The guid field does use the
    # standard format, so replace the title using it.
    manipulate:
      - title:
          from: guid
          extract: ([^/]+)/?$
    preset:
      - torrents
      - tv-new
    regexp:
      reject_excluding:
        # Only want documentaries from this feed.
        - mvgroup
    remove_trackers:
      - hexagon\.cc
      - '\.onion:'
      - tor2web\.com

  # Movies
  supertorrents_movies:
    include:
      - private/supertorrents_movies-rss.yml
    preset:
      - torrents
      - movies
  xtremespeeds_movies:
    include:
      - private/xtremespeeds_movies-rss.yml
    preset:
      - torrents
      - movies
  rlslog:
    rlslog: http://www.rlslog.net/category/movies/
    preset:
      - torrents
      - movies

  apple_trailers:
    interval: 4 hours
    apple_trailers: 480p
    accept_all: yes
    set:
      path: ~/Media/Movies/Trailers/.
