presets:
  global:
    download: ~/Downloads/.

  movies:
    interval: 30 minutes
    quality:
      max: bdrip
      min: r5
    regexp:
      reject:
        - '[\W_]r5[\W_].*?(?:_|\b)(?:line|mic|russian|cam[\W_]*audio)(?:_|\b)'
        - '[\W_]r5[\W_].*?(?:_|\b)read[\W_]+nfo(?:_|\b)'
        - '[\W_]3-?D(?:BD)?\b'
        - '[\W_]ppv(?:-?rip)?\b'
    content_size:
      min: 650
      max: 1750
    seen_movies: strict
    imdb:
      min_score: 6.2
      min_votes: 100
      min_year: 2006
      reject_genres:
        - musical
    custom_movie_path:
      default: ~/Media/Movies/.
      documentary: ~/Media/Movies/Documentaries/.
      foreign: ~/Media/Movies/Foreign/.

  tv:
    only_new: yes
    content_size:
      max: 1500
    manipulate:
      # Recognize webrip quality.
      - title:
          replace:
            regexp: (?i)webrip
            format: dsr
      # Replace the non-standard quality name for a particular ripper.
      - title:
          replace:
            regexp: (?i)ws\.xvid-err0001
            format: hdtv

  tv-series:
    series:
      settings:
        tv:
          min_quality: dsr
          max_quality: dvdrip
          path: ~/Media/TV/%(series_name)s/.
          propers: 3 hours
        documentaries:
          min_quality: dsr
          max_quality: dvdrip
          path: ~/Media/TV/Documentaries/%(series_name)s/.
          propers: 3 hours
        talk_shows:
          min_quality: dsr
          max_quality: dvdrip
          path: ~/Media/TV/Talk Shows/%(series_name)s/.
          propers: 3 hours
    include:
      - private/series.yml

  # Grab the first episode of any new series.
  tv-premieres:
    series_premiere:
      min_quality: hdtv
      max_quality: dvdrip
      path: ~/Media/TV/_NEW_/.
      propers: no
    ## This plugin doesn't exist yet.
    # tvrage:
    #   reject_status:
    #     - canceled/ended
    #   reject_genres:
    #     - children
    #     - dance
    #     - fashion/make-up
    #     - music
    #     - religion
    #     - romance/dating
    #     - soaps
    #     - sports
    #   reject_classifications:
    #     - award show
    #     - game show
    #     - reality
    #     - sports
    #   reject_origin_country:
    #     - au
    ## This plugin is broken and the site's data isn't really good for new
    ## series.
    # thetvdb:
    #   reject_status:
    #     - Ended
    #   reject_genres:
    #     - Children
    #     - Game Show
    #     - Reality
    #     - Soap
    #     - Sport

  torrents:
    regexp:
      reject:
        - '[\W_]+(?:[hx][.-]?264|nuked)(?:_|\b)'
    content_filter:
      reject:
        - '*.m[4k]v'
        - '*.mp4'
        - '*.wmv'
    torrent_scrub: on
    exec:
      auto_escape: yes
      on_output:
        for_accepted: |
          growlnotify -t 'FlexGet: torrent downloaded' -m %(title)s \
            >/dev/null 2>&1
        phase: |
          # This is also run from cron every few minutes.
          nice -n 20 transmission-watchdog

feeds:
  # TV series.
  eztv:
    priority: 1
    interval: 5 minutes
    rss:
      url: http://ezrss.it/feed/
      silent: yes
    preset:
      - torrents
      - tv
      - tv-series
  btn:
    priority: 2
    interval: 5 minutes
    include:
      - private/btn-rss.yml
    preset:
      - torrents
      - tv
      - tv-series
    # Use the scene release name.
    manipulate:
      - title:
          extract: '\[ ([^]]+) \] *$'
  tvt:
    priority: 3
    interval: 5 minutes
    include:
      - private/tvt-rss.yml
    preset:
      - torrents
      - tv
      - tv-series
  torrentvault_tv:
    priority: 5
    interval: 5 minutes
    include:
      - private/torrentvault_tv-rss.yml
    preset:
      - torrents
      - tv
      - tv-series
  thebox:
    # Ratio-based tracker; easy to maintain. UK content.
    priority: 6
    interval: 15 minutes
    rss:
      url: https://thebox.bz/rssdd.xml
      silent: yes
    include:
      - private/thebox-headers.yml
    preset:
      - torrents
      - tv
      - tv-series
    if:
      - "str(now.year) + ')' not in title": reject
    regexp:
      reject_excluding:
        - \((?:XviD|DivX)\).*?\((?:Drama|Mystery)
  bitmetv:
    # Ratio-based tracker; hard to maintain.
    priority: 7
    interval: 5 minutes
    delay: 30 minutes
    include:
      - private/bitmetv-rss.yml
    preset:
      - torrents
      - tv
      - tv-series

  # TV series premieres.
  torrentvault_tv_premieres:
    priority: 22
    interval: 5 minutes
    include:
      - private/torrentvault_tv-rss.yml
    preset:
      - torrents
      - tv
      - tv-premieres
  btn_premieres:
    priority: 23
    interval: 5 minutes
    include:
      - private/btn-rss.yml
    preset:
      - torrents
      - tv
      - tv-premieres
    # Use the scene release name.
    manipulate:
      - title:
          replace:
            regexp: '^[^[]+\[ (\d+) \].*?\[ ([^]]+) \] *$'
            format: '\2 \1'
    if:
      - "not title.endswith(str(now.year))": reject

  # Movies
  xtremespeeds_movies:
    priority: 31
    include:
      - private/xtremespeeds_movies-rss.yml
    preset:
      - torrents
      - movies
  ptp:
    priority: 32
    include:
      - private/ptp-rss.yml
    preset:
      - torrents
      - movies
    regexp:
      reject_excluding:
        - '- (?:XviD|DivX) / DVD / AVI /'
  rlslog:
    priority: 33
    rlslog: http://www.rlslog.net/category/movies/
    preset:
      - torrents
      - movies

  apple_trailers:
    priority: 40
    interval: 4 hours
    only_new: yes
    apple_trailers: 480p
    accept_all: yes
    # Using 'set' allows the path to be recreated if it doesn't exit.
    set:
      path: ~/Media/Movies/Trailers/.
