---
presets:
  global:
    download: ~/Downloads/.

  movies:
    interval: 30 minutes
    quality:
      max: bdrip
      min: r5
    regexp:
      reject:
        - '[\W_]r5[\W_].*?(?:_|\b)(?:mic|russian|cam[\W_]+audio)(?:_|\b)'

    content_size:
      min: 650
      max: 1750
    seen_movies: strict
    imdb:
      min_score: 6.2
      min_votes: 100
      min_year: 2006
      reject_genres:
        - musical
    custom_movie_path:
      default: ~/Media/Movies/.
      documentary: ~/Media/Movies/Documentaries/.
      foreign: ~/Media/Movies/Foreign/.

  tv:
    content_size:
      max: 1500
    quality:
      max: hdtv
      min: dsr

  tv-series:
    series:
      settings:
        tv:
          path: ~/Media/TV/%(series_name)s/.
          propers: 3 hours
        documentaries:
          path: ~/Media/TV/Documentaries/%(series_name)s/.
          propers: 3 hours
        talk_shows:
          path: ~/Media/TV/Talk Shows/%(series_name)s/.
          propers: 3 hours
    include:
      - private/series.yml

  tv-premieres:
    # Grab the first episode of any new series.
    series_premiere: yes
    regexp:
      reject:
        - '[\W_]+(?:PDTV|AU(?:TV)?|Australia(?:n|''?s)?)(_|\b)'
    ## This plugin doesn't exist yet.
    # tvrage:
    #   reject_status:
    #     - canceled/ended
    #   reject_genres:
    #     - children
    #     - dance
    #     - fashion/make-up
    #     - music
    #     - religion
    #     - romance/dating
    #     - soaps
    #     - sports
    #   reject_classifications:
    #     - award show
    #     - game show
    #     - reality
    #     - sports
    #   reject_origin_country:
    #     - au
    ## This plugin is broken and the site's data isn't really good for new
    ## series.
    # thetvdb:
    #   reject_status:
    #     - Ended
    #   reject_genres:
    #     - Children
    #     - Game Show
    #     - Reality
    #     - Soap
    #     - Sport
    # Using 'set' allows the path to be recreated if it doesn't exit.
    set:
      path: ~/Media/TV/_NEW_/.

  torrents:
    regexp:
      reject:
        - '[\W_]+(?:[hx]264|nuked)(?:_|\b)'
    content_filter:
      reject:
        - '*.m[4k]v'
        - '*.wmv'

    # TODO: expand the folder in the finder
    exec:
      auto_escape: yes
      on_output:
        for_accepted: |
          growlnotify -t 'FlexGet: torrent downloaded' -m %(title)s \
            >/dev/null 2>&1
        event: |
          # This is also run from cron every few minutes.
          nice -n 19 transmission-watchdog 2>&1 |
            tee -a /tmp/transmission-watchdog.log |
            # Need to verify some input is present because growlnotify is happy
            # displaying empty messages.
            while read -r l; do
              # Strip off timestamp.
              l=$(expr "$l" : '.\{22\}\(.*\)')
              growlnotify -t 'transmission-watchdog via flexget' -m "$l" \
                >/dev/null 2>&1
            done
          # Remove empty directories after unrarred media file has been
          # viewed and deleted and original rar archive has finished seeding
          # and been removed.
          find ~/Media/{Movies,TV}/. -type f -name .DS_Store \
            -exec rm -f {} + 2>/dev/null
          find ~/Media/{Movies,TV}/. -type d \! -name . -empty -depth \
            -exec rmdir {} + 2>/dev/null

feeds:
  # TV series.
  eztv:
    priority: 1
    interval: 5 minutes
    rss:
      url: http://ezrss.it/feed/
      silent: yes
    preset:
      - torrents
      - tv
      - tv-series
    remove_trackers:
      - hexagon\.cc
      - '\.onion:'
      - tor2web\.com
  btn:
    priority: 2
    interval: 5 minutes
    include:
      - private/btn.yml
    preset:
      - torrents
      - tv
      - tv-series
    regexp:
      reject:
        - \bAutofill Fail(?:ed)?\b
  scenetime_tv:
    priority: 3
    interval: 5 minutes
    include:
      - private/scenetime_tv-rss.yml
    preset:
      - torrents
      - tv
      - tv-series
  torrentvault_tv:
    priority: 4
    interval: 5 minutes
    include:
      - private/torrentvault_tv-rss.yml
    preset:
      - torrents
      - tv
      - tv-series
  thebox:
    priority: 5
    interval: 15 minutes
    rss:
      url: http://thebox.bz/rssdd.xml
      silent: yes
    include:
      - private/thebox-headers.yml
    preset:
      - torrents
      - tv
      - tv-series
    regexp:
      reject_excluding:
        - 201\d\).*?\((?:XviD|DivX)\).*?\((?:Drama|Horizon|Mystery)
  theempire:
    priority: 6
    interval: 15 minutes
    rss:
      url: http://theempire.bz/rssdd.xml
      silent: yes
    include:
      - private/theempire-headers.yml
    preset:
      - torrents
      - tv
      - tv-series
    regexp:
      reject_excluding:
        - 201\d\).*?\((?:XviD|DivX)\).*?\((?:Documentary|Drama|Mystery)

  # TV series premieres.
  eztv_premieres:
    priority: 20
    interval: 10 minutes
    rss:
      url: http://ezrss.it/feed/
      silent: yes
    preset:
      - torrents
      - tv
      - tv-premieres
    regexp:
      reject_excluding:
        # Only want documentaries from this feed.
        - mvgroup
    remove_trackers:
      - hexagon\.cc
      - '\.onion:'
      - tor2web\.com
  torrentvault_tv_premieres:
    priority: 21
    interval: 5 minutes
    include:
      - private/torrentvault_tv-rss.yml
    preset:
      - torrents
      - tv
      - tv-premieres
  scenetime_tv_premieres:
    priority: 22
    interval: 5 minutes
    include:
      - private/scenetime_tv-rss.yml
    preset:
      - torrents
      - tv
      - tv-premieres

  # Movies
  xtremespeeds_movies:
    priority: 30
    include:
      - private/xtremespeeds_movies-rss.yml
    preset:
      - torrents
      - movies
  rlslog:
    priority: 31
    rlslog: http://www.rlslog.net/category/movies/
    preset:
      - torrents
      - movies

  apple_trailers:
    priority: 40
    interval: 4 hours
    apple_trailers: 480p
    accept_all: yes
    # Using 'set' allows the path to be recreated if it doesn't exit.
    set:
      path: ~/Media/Movies/Trailers/.
