---
presets:
  global:
    download: ~/Downloads/.
    rss:
      silent: yes

  movies:
    interval: 2 hours
    content_size:
      min: 650
      max: 1750
    regexp:
      reject_excluding:
        - '[\W_]+(?:r5|b[dr]rip|dvd(?:rip|scr))':
            from: title
    seen_movies: strict
    imdb:
      min_score: 6.2
      min_votes: 200
      min_year: 2006
      reject_genres:
        - music
        - musical
    set:
      path: ~/Media/Movies/.

  tv:
    content_size:
      min: 150
      max: 800
    series:
      settings:
        tv:
          path: ~/Media/TV/%(series_name)s/.
          propers: 3 hours
        documentaries:
          path: ~/Media/Documentaries/%(series_name)s/.
        talk_shows:
          path: ~/Media/TV/Talk Shows/%(series_name)s/.
    include:
      - private/series.yml

  # Grab the first episode of any new program.
  # TODO: use thetvdb or tvrage to avoid downloading duplicates, old
  #   shows, and shows with unwanted genres, etc.
  tv-new:
    regexp:
      accept:
        - '[\W_]+(?:s0?1[\W_]*ep?0?1|0?1x0?1)(?!\d)':
            path: ~/Media/TV/_NEW_/.

  torrent:
    regexp:
      reject:
        - '[\W_]+x264'
        - '[\W_]+(?:72|108)0p'
        - '[\W_]+nuked'
    # TODO: expand the folder in the finder
    exec: |
      echo %(title)s | growlnotify -a Transmission -t 'Torrent downloaded' &&
      transmission-watchdog

feeds:
  supertorrents_tv:
    priority: 1
    interval: 5 minutes
    include:
      - private/supertorrents_tv-rss.yml
    preset:
      - torrent
      - tv
      - tv-new
  torrentvault_tv:
    priority: 2
    interval: 5 minutes
    include:
      - private/torrentvault_tv-rss.yml
    preset:
      - torrent
      - tv
      - tv-new
  torrentday_tv:
    priority: 3
    interval: 5 minutes
    include:
      - private/torrentday_tv-rss.yml
    preset:
      - torrent
      - tv
  xtremespeeds_tv:
    priority: 4
    interval: 5 minutes
    include:
      - private/xtremespeeds_tv-rss.yml
    preset:
      - torrent
      - tv
      - tv-new
  eztv:
    priority: 5
    interval: 10 minutes
    rss:
      url: http://ezrss.it/feed/
    preset:
      - torrent
      - tv
    remove_trackers:
      - hexagon\.cc
      - '\.onion:'
      - tor2web\.com
  thebox:
    interval: 15 minutes
    rss:
      url: http://thebox.bz/rssdd.xml
    include:
      - private/thebox-headers.yml
    preset:
      - torrent
      - tv
    regexp:
      reject_excluding:
        - 201\d\).*\(XviD\).*\((?:Drama|Mystery|Gardening)
      reject:
        # This feed uses a different episode numbering for this series.
        - ^[\W_]*midsomer[\W_]+murders

  xtremespeeds_movies:
    interval: 15 minutes
    include:
      - private/xtremespeeds_movies-rss.yml
    preset:
      - torrent
      - movies

  daves_trailer_page:
    interval: 4 hours
    html:
      url: http://www.davestrailerpage.co.uk/
      title_from: link
    regexp:
      accept:
        - '^(?:hd 480p|trailer(?: |$))':
            from: title
    extension: mov
    # Some of the links are to apple.com
    headers:
      User-Agent: QuickTime/7.6.2
    set:
      path: ~/Media/Movies/Trailers/.
