---
presets:
  global:
    download: ~/Downloads/.

  movies:
    interval: 2 hours
    torrent_size:
      min: 650
      max: 1750
    regexp:
      reject_excluding:
        - '[\W_]+b[dr]rip'
        - '[\W_]+dvd(?:rip|scr)'
        - '[\W_]+r5'
    seen_movies: strict
    imdb:
      min_score: 6.2
      min_votes: 200
      min_year: 2006
      reject_genres:
        - music
        - musical
    set:
      path: ~/Media/Movies/.

  tv:
    torrent_size:
      min: 150
      max: 800
    series:
      settings:
        tv:
          path: ~/Media/TV/%(series_name)s/.
    include:
      - private/series.yml
    # Grab the first episode of any new program.
    # TODO: use thetvdb or tvrage to avoid downloading duplicates, old
    #   shows, and shows with unwanted genres, etc.
    regexp:
      accept:
        - '[\W_]+(?:s0?1[\W_]*ep?0?1|0?1x0?1)(?!\d)':
            path: ~/Media/TV/_NEW_/.

  torrent:
    regexp:
      reject:
        - '[\W_]+x264'
        - '[\W_]+(?:72|108)0p'
        - '[\W_]+nuked'
    include:
      - private/email.yml
      - private/transmissionrpc.yml
    exec: |
      # Remove completed, stopped torrents.
      transmission-remote -l | awk '/ 100%% .* Stopped / {print $1}' |
        paste -s -d, - | xargs -I \{\} transmission-remote -t \{\} -r &&
      rm -f %(output)s

  torrent-public:
    set:
      ratio: 0
      maxupspeed: 5

feeds:
  xtremespeeds_tv:
    interval: 5 minutes
    include:
      - private/xtremespeeds_tv-rss.yml
    preset:
      - torrent
      - tv
  eztv:
    interval: 10 minutes
    rss: http://ezrss.it/feed/
    preset:
      - torrent
      - torrent-public
      - tv
  thebox:
    interval: 15 minutes
    rss: http://thebox.bz/rssdd.xml
    include:
      - private/thebox-headers.yml
    preset:
      - torrent
      - tv
    regexp:
      reject_excluding:
        - xvid
      reject:
        # This feed uses a different episode numbering for this series.
        - ^[\W_]*midsomer[\W_]+murders
  torrentvault_tv:
    interval: 20 minutes
    # Prefer non-rar files from other feeds.
    delay: 30 minutes
    include:
      - private/torrentvault_tv-rss.yml
    preset:
      - torrent
      - tv

  xtremespeeds_movies:
    interval: 15 minutes
    include:
      - private/xtremespeeds_movies-rss.yml
    preset:
      - torrent
      - movies

  daves_trailer_page:
    interval: 4 hours
    html:
      url: http://www.davestrailerpage.co.uk/
      title_from: contents
    limit_new: 1
    regexp:
      accept:
        - '^(?:hd 480p|trailer(?: |$))':
            from: title
    # Some of the links are to apple.com
    headers:
      User-Agent: QuickTime/7.6.2
    set:
      path: ~/Media/Movies/Trailers/.

  ted_talks:
    interval: 3 hours
    limit_new: 1
    rss: http://feeds.feedburner.com/tedtalks_video
    accept_all: yes
    set:
      path: ~/Media/Talks/.
    exec: |
      # Extract the audio stream from the video.
      ffmpeg -y -vn -acodec copy -i %(output)s -map_meta_data
        %(output)s:%(output)s.m4a %(output)s.m4a >/dev/null 2>&1 &&
      # Change the file extension so it is recognized as an audiobook.
      mv -f %(output)s.m4a %(output)s.m4b &&
      # Add the new audio file to iTunes.
      osascript -e '
        tell application "iTunes" to add posix file "%(output)s.m4b"
      ' >/dev/null 2>&1 &&
      rm -f %(output)s %(output)s.m4b
