---
presets:
  global:
    download: ~/Downloads/.
    include:
      - ~/.flexget/private/email.yml
      # - ~/.flexget/private/transmissionrpc.yml
    regexp:
      reject:
        - '[\W_]+x264'
        - '[\W_]+(72|108)0p'
        - '[\W_]+nuked'

  movies:
    interval: 2 hours
    torrent_size:
      min: 650
      max: 1750
    regexp:
      reject_excluding:
        - '[\W_]+b[dr]rip'
        - '[\W_]+dvd(rip|scr)'
        - '[\W_]+r5'
    seen_movies: strict
    imdb:
      min_score: 6.2
      min_votes: 200
      min_year: 2006
      reject_genres:
        - music
        - musical
    set:
      path: ~/Movies/.

  tv:
    torrent_size:
      min: 150
      max: 800
    set:
      path: ~/Movies/TV Episodes/%(series_name)s/.
    include:
      - ~/.flexget/private/series.yml

  # Switch to the transmissionrpc plugin when it matures. It can only add
  # torrents via URL, and this will fail on some private trackers which
  # require certain cookies to be present.
  tracker-private:
    exec: |
      # Add torrent.
      transmission-remote -a '%(output)s' &&
      growlnotify -a Transmission -t "Torrent added" -m "%(title)s" &&
      # Remove completed, stopped torrents.
      transmission-remote -l | awk '/ 100%% .* Stopped / {print $1}' |
        paste -s -d, - | xargs -I \{\} transmission-remote -t \{\} -r &&
      # Remove torrent file.
      rm -f '%(output)s'
  tracker-public:
    set:
      ratio: 0
      maxupspeed: 5
    exec: |
      # Add torrent.
      transmission-remote -a '%(output)s' &&
      growlnotify -a Transmission -t "Torrent added" -m "%(title)s" &&
      transmission-remote -t %(torrent_info_hash)s -tu 5 -sr 0 &&
      # Remove completed, stopped torrents.
      transmission-remote -l | awk '/ 100%% .* Stopped / {print $1}' |
        paste -s -d, - | xargs -I \{\} transmission-remote -t \{\} -r &&
      # Remove torrent file.
      rm -f '%(output)s'

feeds:
  xtremespeeds_tv:
    interval: 5 minutes
    include:
      - ~/.flexget/private/xtremespeeds_tv-rss.yml
    preset:
      - tracker-private
      - tv
  eztv:
    interval: 10 minutes
    rss: http://www.ezrss.it/feed/
    preset:
      - tracker-public
      - tv
  thebox:
    interval: 15 minutes
    rss: http://thebox.bz/rssdd.xml
    include:
      - ~/.flexget/private/thebox-headers.yml
    preset:
      - tracker-private
      - tv
    regexp:
      reject:
        # This feed uses a different episode numbering for this series.
        - ^[\W_]*midsomer[\W_]+murders
  torrentvault_tv:
    interval: 5 minutes
    # Prefer non-rar files from other feeds.
    delay: 30 minutes
    include:
      - ~/.flexget/private/torrentvault_tv-rss.yml
    preset:
      - tracker-private
      - tv

  xtremespeeds_movies:
    interval: 15 minutes
    include:
      - ~/.flexget/private/xtremespeeds_movies-rss.yml
    preset:
      - tracker-private
      - movies
  rlslog_movies:
    rlslog: http://www.rlslog.net/category/movies/
    preset:
      - tracker-public
      - movies
  scenereleases_movies:
    scenereleases: http://scenereleases.info/category/movies
    preset:
      - tracker-public
      - movies
