---
presets:
  global:
    download: ~/Downloads/.
    include:
      - private/email.yml
    regexp:
      reject:
        - '[\W_]+x264'
        - '[\W_]+(72|108)0p'
        - '[\W_]+nuked'

  movies:
    interval: 2 hours
    torrent_size:
      min: 650
      max: 1750
    regexp:
      reject_excluding:
        - '[\W_]+b[dr]rip'
        - '[\W_]+dvd(rip|scr)'
        - '[\W_]+r5'
    seen_movies: strict
    imdb:
      min_score: 6.2
      min_votes: 200
      min_year: 2006
      reject_genres:
        - music
        - musical
    set:
      path: ~/Movies/.

  tv:
    torrent_size:
      min: 150
      max: 800
    series:
      settings:
        tv:
          path: ~/Movies/TV Series/%(series_name)s/.
    include:
      - private/series.yml
    # Grab the first episode of any new program.
    # TODO: use thetvdb or tvrage to avoid downloading duplicates, old
    #   shows, and shows with unwanted genres, etc.
    regexp:
      accept:
        - '[\W_]+(?:s0?1[\W_]*ep?0?1|0?1x0?1)(?!\d)':
            path: ~/Movies/TV Series/_NEW_/.

  torrent:
    include:
      - private/transmissionrpc.yml
    exec: |
      echo %(title)s | growlnotify -a Transmission -t 'Torrent added' &&
      # Remove completed, stopped torrents.
      transmission-remote -l | awk '/ 100%% .* Stopped / {print $1}' |
        paste -s -d, - | xargs -I \{\} transmission-remote -t \{\} -r &&
      # Move torrent to watched directory. If transmission is not running
      # when the torrent is downloaded, it should be found when it restarts.
      mv -f %(output)s ~/Downloads/.

  torrent-public:
    set:
      ratio: 0
      maxupspeed: 5

feeds:
  xtremespeeds_tv:
    interval: 5 minutes
    include:
      - private/xtremespeeds_tv-rss.yml
    preset:
      - torrent
      - tv
  eztv:
    interval: 10 minutes
    rss: http://www.ezrss.it/feed/
    preset:
      - torrent
      - torrent-public
      - tv
  thebox:
    interval: 15 minutes
    rss: http://thebox.bz/rssdd.xml
    include:
      - private/thebox-headers.yml
    preset:
      - torrent
      - tv
    regexp:
      reject:
        # This feed uses a different episode numbering for this series.
        - ^[\W_]*midsomer[\W_]+murders
  torrentvault_tv:
    interval: 20 minutes
    # Prefer non-rar files from other feeds.
    delay: 30 minutes
    include:
      - private/torrentvault_tv-rss.yml
    preset:
      - torrent
      - tv

  xtremespeeds_movies:
    interval: 15 minutes
    include:
      - private/xtremespeeds_movies-rss.yml
    preset:
      - torrent
      - movies
